<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Question;

/**
 * ChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChoixQuestion(Question $question) {
        $qb = $this->createQueryBuilder('c');
        $qb -> leftJoin('c.questions', 'q');
        $qb -> where($qb->expr()->eq('q.id', ':question'))
                ->setParameter('question', $question->getId());
        $qb -> orderby('c.rang', 'ASC');

        return $qb;
    }
}