<?php

namespace AppBundle\Repository;

/**
 * Questionnaire_IndividualiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Questionnaire_IndividualiseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuestionnairesAcompleter($user, $colonneSignature){

        $qb= $this->createQueryBuilder('q');
        $qb->innerJoin('AppBundle:Questionnaire', 'q2', 'WITH', 'q2.id=q.questionnaire');
        $qb ->where("q2.dateOuverture < :date");
        if("signatureTuteur"==$colonneSignature){
            $qb ->andWhere("q.signatureTuteur=false");
        }elseif ("signatureMap"==$colonneSignature){
            $qb ->andWhere("q.signatureMap=false");
        }elseif ("signatureEtudiant"==$colonneSignature){
            $qb ->andWhere("q.signatureEtudiant=false");
        }

        $i=0;
        $nbContrats = sizeof($user->getContrats());
        foreach ($user->getContrats() as $contrat) {
            if($i==0){
                $qb ->andWhere("q.contrat = :idContrat");
            }elseif ($i<$nbContrats && $i>0){
                $qb ->orWhere("q.contrat = :idContrat");
            }

            $qb->setParameter("idContrat", $contrat->getId());
            $i++;
        }


        $qb->setParameter("date", new \DateTime());
        $qb->addOrderBy("q2.dateFermeture");

        return $qb
            ->getQuery()
            ->getResult();
    }
}
