<?php

namespace AppBundle\Repository;

/**
 * Questionnaire_IndividualiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Questionnaire_IndividualiseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuestionnairesAcompleter($user, $role){

        $qb= $this->createQueryBuilder('q');
        $qb->innerJoin('AppBundle:Questionnaire', 'q2', 'WITH', 'q2.id=q.questionnaire');
        $qb ->where("q2.dateOuverture < :date");

        switch ($role) {
            case "ROLE_ETUDIANT":
                $qb ->andWhere("q.signatureEtudiant=false");
                break;
            case "ROLE_TUTEUR":
                $qb ->andWhere("q.signatureTuteur=false");
                break;
            case "ROLE_MAP":
                $qb ->andWhere("q.signatureMap=false");
                break;
        }

        $i=1;
        $nbContrats = sizeof($user->getContrats());
        $reqContrat="(";
        foreach ($user->getContrats() as $contrat) {
            if($i==1){
                $reqContrat.= 'q.contrat ='.$contrat->getId().'';
            }elseif($i>1){
                $reqContrat.= 'OR q.contrat ='.$contrat->getId().'';
            }
            $i++;
        }
        $qb ->andWhere($reqContrat.')');

        $date = new \DateTime();

        $qb->setParameter("date", $date->format("Y-m-d"));
        $qb->addGroupBy("q2.id");
        $qb->addOrderBy("q2.dateFermeture");
        $qb->distinct();

        return $qb
            ->getQuery()
            ->getResult();
    }
}