<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Questionnaire;
use AppBundle\Entity\User;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReponses(Questionnaire $questionnaire, User $user) {
        $qb= $this->createQueryBuilder('r');
        $qb->leftJoin('AppBundle:Questionnaire_Individualise', 'q', 'WITH', 'q=r.questionnaire_individualise');
        $qb->where("q.questionnaire = :questionnaire");

        $i=1;
        $reqContrat = "(";
        foreach ($user->getContrats() as $contrat) {
            if ($i==1) {
                $reqContrat .= 'q.contrat ='.$contrat->getId().'';
            } elseif ($i>1) {
                $reqContrat .= 'or q.contrat ='.$contrat->getId().'';
            }
            $i++;
        }
        $qb->andWhere($reqContrat.')');
        $qb->setParameter("questionnaire", $questionnaire->getId());

        return $qb
            ->getQuery()
            ->getResult();
    }
}