<?php

namespace AppBundle\Repository;

/**
 * TypeQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
