services:
    app.user.manager:
        class: AppBundle\Manager\UserManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router', '@security.token_storage', '@fos_user.user_manager' ]

    app.questionnaire.manager:
        class: AppBundle\Manager\QuestionnaireManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

    app.question.manager:
        class: AppBundle\Manager\QuestionManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

    app.choix.manager:
        class: AppBundle\Manager\ChoixManager
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

    app.typeDocument.manager:
            class: AppBundle\Manager\TypeDocumentManager
            arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

    app.anneeScolaire.manager:
            class: AppBundle\Manager\AnneeScolaireManager
            arguments: [ '@doctrine.orm.entity_manager', '@form.factory', '@router' ]

    fos_user.doctrine_registry:
        alias: doctrine